IMPLEMENTATION = ../hollow_heap/hollow_heap_base.h ../pairing_heap/pairing_heap.h
CPP_ARGS = --std=c++11 -Wall -O3

dijkstra: $(IMPLEMENTATION) dijkstra.cpp
	g++ $(CPP_ARGS) -o dijkstra dijkstra.cpp

clean:
	rm -f dijkstra
